### ISSUE TITLE
How to get chat history in telegram group chat using telegram bot?

### ISSUE THREAD

**Issue by ghost** [SuperStar0718/ChatGPT-Telegram-Bot#1]
Hello.
I am going to get chat history in telegram using telegram bot.
I've tried like this:
token = self.config['token']
# get the chat ID
chat_id = update.message.chat_id
url = f'https://api.telegram.org/bot{token}/getUpdates'
while True:
            params = {'limit':5, 'timeout':10, 'offset':offset}
            print('offset:',offset)
            response = requests.get(url,params)
            data = response.json()
            print('data:',data)
            if not data['result']:
                break

            for temp in data['result']:
                message = temp['message']
                timestamp = message['date']
                # if start_time <= timestamp <= end_time:
                text = message['text']
                sender = message['from']['username']
                output+=(f'{sender}: {text}\n')
                print(temp['update_id'])

            offset = temp['update_id'] + 1

But it didn't work.
Can you help me?

**Comment by SuperStar0718** [comment]
You can't get all chat history using getUpdate api.
you have to use getmessages method of TelegramClient.
Here is the sample code:
client = TelegramClient(entity, api_id, api_hash)
client.start()
 messages = await client.get_messages(chat_id, limit=5, offset_date=timestamp)

**Comment by ghost** [comment]
It works very well.
Thank you very much.

**Comment by SuperStar0718** [comment]
Welcome.
If you have any problem with telegram bot, Please aske me.
